# Generated by Django 6.0.1 on 2026-02-02 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dairy', '0001_initial'),
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='date')),
                ('symptoms', models.TextField(verbose_name='symptoms')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='temperature (°C)')),
                ('diagnosis', models.CharField(blank=True, max_length=500, verbose_name='diagnosis')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='severity')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='health_events/', verbose_name='photo')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='dairy.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_events_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'health event',
                'verbose_name_plural': 'health events',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='date')),
                ('treatment_name', models.CharField(max_length=200, verbose_name='treatment/medication')),
                ('dose', models.CharField(blank=True, max_length=100, verbose_name='dose')),
                ('route', models.CharField(blank=True, choices=[('oral', 'Oral'), ('injection_im', 'Injection (IM)'), ('injection_iv', 'Injection (IV)'), ('injection_sc', 'Injection (SC)'), ('topical', 'Topical'), ('intramammary', 'Intramammary'), ('other', 'Other')], max_length=20, verbose_name='route')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost')),
                ('milk_withdrawal_days', models.PositiveIntegerField(default=0, help_text='Number of days milk should not be sold after treatment', verbose_name='milk withdrawal (days)')),
                ('meat_withdrawal_days', models.PositiveIntegerField(default=0, verbose_name='meat withdrawal (days)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_administered', to=settings.AUTH_USER_MODEL)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='dairy.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
                ('health_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='health.healthevent')),
            ],
            options={
                'verbose_name': 'treatment',
                'verbose_name_plural': 'treatments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='date administered')),
                ('vaccine_name', models.CharField(max_length=200, verbose_name='vaccine name')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='batch number')),
                ('dose', models.CharField(blank=True, max_length=100, verbose_name='dose')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='next due date')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_administered', to=settings.AUTH_USER_MODEL)),
                ('cow', models.ForeignKey(blank=True, help_text='Leave blank for herd-wide vaccination', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dairy.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
            ],
            options={
                'verbose_name': 'vaccination',
                'verbose_name_plural': 'vaccinations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_name', models.CharField(max_length=200, verbose_name='vaccine name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('interval_months', models.PositiveIntegerField(help_text='Months between vaccinations', verbose_name='interval (months)')),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
            ],
            options={
                'verbose_name': 'vaccination schedule',
                'verbose_name_plural': 'vaccination schedules',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawal_type', models.CharField(choices=[('milk', 'Milk Withdrawal'), ('meat', 'Meat Withdrawal')], default='milk', max_length=10, verbose_name='type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='dairy.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='health.treatment')),
            ],
            options={
                'verbose_name': 'withdrawal',
                'verbose_name_plural': 'withdrawals',
                'ordering': ['-end_date'],
            },
        ),
    ]
