# Generated by Django 6.0.1 on 2026-02-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('yield_drop', 'Yield Drop'), ('vaccine_due', 'Vaccine Due'), ('withdrawal_active', 'Withdrawal Active'), ('task_missed', 'Task Missed'), ('health_event', 'Health Event'), ('payment_overdue', 'Payment Overdue'), ('system', 'System')], max_length=30, verbose_name='type')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='severity')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('muted', 'Muted')], default='open', max_length=20, verbose_name='status')),
                ('entity_type', models.CharField(blank=True, help_text="e.g., 'Cow', 'FeedItem', 'Task'", max_length=50, verbose_name='entity type')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='entity ID')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, verbose_name='resolution note')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('yield_drop', 'Yield Drop'), ('vaccine_due', 'Vaccine Due'), ('withdrawal_active', 'Withdrawal Active'), ('task_missed', 'Task Missed'), ('health_event', 'Health Event'), ('payment_overdue', 'Payment Overdue'), ('system', 'System')], max_length=30, verbose_name='alert type')),
                ('is_enabled', models.BooleanField(default=True)),
                ('parameters', models.JSONField(default=dict, help_text='Rule-specific parameters')),
                ('notify_owner', models.BooleanField(default=True)),
                ('notify_workers', models.BooleanField(default=False)),
                ('notification_channels', models.JSONField(default=list, help_text='List of channels: in_app, sms, email, etc.')),
            ],
            options={
                'verbose_name': 'alert rule',
                'verbose_name_plural': 'alert rules',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification')], default='in_app', max_length=20, verbose_name='channel')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='queued', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, verbose_name='error')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
