# Generated by Django 6.0.1 on 2026-02-02 12:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_number', models.CharField(max_length=50, verbose_name='tag number')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='breed')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='purchase price')),
                ('status', models.CharField(choices=[('heifer', 'Heifer'), ('milking', 'Milking'), ('dry', 'Dry'), ('pregnant', 'Pregnant'), ('sick', 'Sick'), ('sold', 'Sold'), ('dead', 'Dead')], default='heifer', max_length=20, verbose_name='status')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cows/', verbose_name='photo')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cow',
                'verbose_name_plural': 'cows',
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='CowStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'cow status history',
                'verbose_name_plural': 'cow status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('date', models.DateField(verbose_name='date')),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('once_daily', 'Once Daily')], max_length=20, verbose_name='session')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='liters')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'milk log',
                'verbose_name_plural': 'milk logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilkProductionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cow_count', models.PositiveIntegerField(default=0)),
                ('avg_liters_per_cow', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('morning_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evening_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'milk production summary',
                'verbose_name_plural': 'milk production summaries',
                'ordering': ['-date'],
            },
        ),
    ]
