# Generated by Django 6.0.1 on 2026-02-02 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dairy', '0001_initial'),
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm'),
        ),
        migrations.AddField(
            model_name='cow',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='dairy.cow'),
        ),
        migrations.AddField(
            model_name='cowstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cowstatushistory',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='dairy.cow'),
        ),
        migrations.AddField(
            model_name='milklog',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_logs', to='dairy.cow'),
        ),
        migrations.AddField(
            model_name='milklog',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm'),
        ),
        migrations.AddField(
            model_name='milklog',
            name='milked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_logs_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milklog',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_revisions', to='dairy.milklog'),
        ),
        migrations.AddField(
            model_name='milkproductionsummary',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_summaries', to='farm.farm'),
        ),
        migrations.AlterUniqueTogether(
            name='cow',
            unique_together={('farm', 'tag_number')},
        ),
        migrations.AlterUniqueTogether(
            name='milkproductionsummary',
            unique_together={('farm', 'date')},
        ),
    ]
