# Generated by Django 4.2.27 on 2026-02-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL for the cow', max_length=500, verbose_name='image URL'),
        ),
    ]
