# Generated by Django 6.0.1 on 2026-02-02 12:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('buyer_type', models.CharField(choices=[('walk_in', 'Walk-in'), ('regular', 'Regular Customer'), ('dairy_collection_center', 'Dairy Collection Center')], default='regular', max_length=30, verbose_name='type')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='credit limit')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
            ],
            options={
                'verbose_name': 'buyer',
                'verbose_name_plural': 'buyers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='date')),
                ('channel', models.CharField(choices=[('walk_in', 'Walk-in'), ('regular_customer', 'Regular Customer'), ('dairy_collection_center', 'Dairy Collection Center')], default='walk_in', max_length=30, verbose_name='channel')),
                ('liters_sold', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='liters sold')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price per liter')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], default='cash', max_length=20, verbose_name='payment method')),
                ('paid_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='paid', max_length=20, verbose_name='payment status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('withdrawal_override', models.BooleanField(default=False, help_text='Sale approved despite active withdrawal', verbose_name='withdrawal override')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.buyer')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_recorded', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_overrides_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='date')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer')], max_length=20, verbose_name='method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('reference', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100, verbose_name='reference')),
                ('payer_phone', models.CharField(blank=True, max_length=20, verbose_name='payer phone')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
