# Generated by Django 6.0.1 on 2026-02-02 12:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dairy', '0001_initial'),
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('category', models.CharField(choices=[('concentrate', 'Concentrate'), ('roughage', 'Roughage'), ('supplement', 'Supplement'), ('mineral', 'Mineral'), ('other', 'Other')], default='concentrate', max_length=20, verbose_name='category')),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('bags', 'Bags'), ('bales', 'Bales'), ('liters', 'Liters'), ('sacks', 'Sacks')], default='kg', max_length=20, verbose_name='default unit')),
                ('qr_code', models.CharField(blank=True, max_length=100, verbose_name='QR code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Alert when stock falls below this level', max_digits=10, verbose_name='reorder level')),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Average or last purchase cost', max_digits=10, null=True, verbose_name='cost per unit')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
            ],
            options={
                'verbose_name': 'feed item',
                'verbose_name_plural': 'feed items',
                'ordering': ['name'],
                'unique_together': {('farm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='purchase date')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantity')),
                ('unit', models.CharField(max_length=20, verbose_name='unit')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='unit price')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total cost')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='supplier')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='feed_receipts/', verbose_name='receipt')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='feeds.feeditem')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_purchases_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feed purchase',
                'verbose_name_plural': 'feed purchases',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='date')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantity used')),
                ('unit', models.CharField(max_length=20, verbose_name='unit')),
                ('scan_method', models.CharField(choices=[('qr_scan', 'QR Scan'), ('manual', 'Manual Entry')], default='manual', max_length=20, verbose_name='entry method')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('cow', models.ForeignKey(blank=True, help_text='Optional: specific cow if tracking per-cow feeding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_usage', to='dairy.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='feeds.feeditem')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_usage_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feed usage log',
                'verbose_name_plural': 'feed usage logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantity on hand')),
                ('unit', models.CharField(max_length=20, verbose_name='unit')),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True, verbose_name='last restocked')),
                ('last_usage_at', models.DateTimeField(blank=True, null=True, verbose_name='last usage')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
                ('feed_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='feeds.feeditem')),
            ],
            options={
                'verbose_name': 'inventory balance',
                'verbose_name_plural': 'inventory balances',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('movement_type', models.CharField(choices=[('purchase_in', 'Purchase In'), ('usage_out', 'Usage Out'), ('adjustment', 'Manual Adjustment'), ('transfer', 'Transfer'), ('loss', 'Loss/Wastage')], max_length=20, verbose_name='type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('unit', models.CharField(max_length=20, verbose_name='unit')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance before')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance after')),
                ('source_type', models.CharField(blank=True, help_text="e.g., 'FeedPurchase', 'FeedUsageLog'", max_length=50, verbose_name='source type')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='source ID')),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='farm.farm')),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='feeds.feeditem')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inventory movement',
                'verbose_name_plural': 'inventory movements',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
